### PR TITLE
Fix 23

### PR DESCRIPTION
**Pull request by teythoon**
This builds upon my previous patch series #25.

### CODE REVIEW

**Comment by conradkdotcom** [comment]
Hi @teythoon ! Thanks for this PR :+1:  and sorry for the delay. I've been a bit busy these last few days, but I hope to have a closer look at this PR the coming weekend. I'll keep you posted either way. Cheers

**Comment by conradkdotcom** [comment]
Hi again @teythoon ! Looks good to me.

There seems to be a conflict after I merged your other PR #25 . Would you mind having a look at it ?

As soon as it's fixed, I can merge and publish to crates.io.

**Comment by teythoon** [comment]
> There seems to be a conflict after I merged your other PR #25 . Would you mind having a look at it ?

Github folded my two commits into one when you merged #25.  That is certainly annoying.  I'll update this pull request.

> As soon as it's fixed, I can merge and publish to crates.io.

Thanks!

**Comment by conradkdotcom** [comment]
@teythoon Thanks again for this. Looks great ! I'm thinking we can probably remove all functions but `read_password_from_tty` before publishing to crates.io, since `read_password_from_tty` allows prompting and is better than reading straight from `stdin`. What do  you think ?

**Comment by conradkdotcom** [comment]
@teythoon Or maybe we need to keep those functions for when no tty is available ?

**Pull request merged**
